### ISSUE TITLE
how to fix this

### ISSUE THREAD

**Issue by devmchedloo** [NooberPro/minecraft-discord-bot#11]
![image](https://github.com/NooberPro/minecraft-discord-bot/assets/92822402/2b45f8e7-eb4b-4062-bf77-33a2ca9a6382)

**Comment by NooberPro** [comment]
Here is how you fix it go to `src` folder and then you will see `data.json` file and edit the file like this. 

```json
{
  "playerCountStats": null,
  "autoChangeStatus": []
}
```

Hope you understand this and fixed it.
Did you by any chance deleted the player count channel that bot created or you put the invalid channel in the config?
