### ISSUE TITLE
Can u fix?

### ISSUE THREAD

**Issue by NotPankajxD** [NooberPro/minecraft-discord-bot#14]
![Screenshot_2024-04-15-17-57-54-32_40deb401b9ffe8e1df2f1cc5ba480b12](https://github.com/NooberPro/minecraft-discord-bot/assets/149930118/8b6ea621-0443-41ef-b47b-0d20b221de5c)
![Screenshot_2024-04-15-17-57-50-30_40deb401b9ffe8e1df2f1cc5ba480b12](https://github.com/NooberPro/minecraft-discord-bot/assets/149930118/b2282eb8-c593-4b71-be34-1a9c7cc7125e)
![Screenshot_2024-04-15-17-57-42-57_40deb401b9ffe8e1df2f1cc5ba480b12](https://github.com/NooberPro/minecraft-discord-bot/assets/149930118/6b89d60c-69bb-4c90-92a5-a878c84dfaaf)

**Comment by NotPankajxD** [comment]
Bro how i install dependencies?

**Comment by NooberPro** [comment]
Hey is your issue fixed and if please close this issue
