### ISSUE TITLE
Add Set Server Please

### ISSUE THREAD

**Issue by vanevgt** [NooberPro/minecraft-discord-bot#6]
Your bot really works perfectly I used replit to run it & i have big communityMC

so I thought
add features like /Setserver {ip} {port} {type} would be great 

so the community can promote their servers for free in my discord server

**Comment by NooberPro** [comment]
Thank you for using my bot. If you can please give a star.

Do you want status message that your community promoted to updated every minute like auto changing status message.

**Comment by vanevgt** [comment]
added star +1 , you could say it like that, if it's too difficult,  just add more server ip:port line then give like 1 hour delay and it willchange to another server.

would be even better if people could change their own ip:port without the owner help
There are too many bot status servers with privately owned servers, imagine if they could advertise their servers creating a healthy community / meeting new friends XD

**Comment by NooberPro** [comment]
I will try to add the feature in next update.
Also thinking to remove the config file and using /setup like command.
Thank for the feedback.

**Comment by NooberPro** [comment]
Hello there, the feature you requested has been added. 
Thank you for patience.  Feedback is appreciated.
