### ISSUE TITLE
how can i fix it ?

### ISSUE THREAD

**Issue by Prokash18Paul** [NooberPro/minecraft-discord-bot#8]
![image](https://github.com/NooberPro/minecraft-discord-bot/assets/155884068/8a5a6bbb-176f-4427-845c-aa4f41863ad1)

**Comment by NooberPro** [comment]
To fix that error, you have to enable all Privileged Gateway Intents in Bot's Section in your Application.

![fix](https://github.com/NooberPro/minecraft-discord-bot/assets/109412782/4b68711f-9f32-4d16-b364-9dd707c474c8)

**Comment by Prokash18Paul** [comment]
Thanks you sir

**Comment by Prokash18Paul** [comment]
and sir there's another problem
![image](https://github.com/NooberPro/minecraft-discord-bot/assets/155884068/4638694d-6699-4eae-9a8a-7ba65636c540)

**Comment by Prokash18Paul** [comment]
sit how can add multiple vote links ?

**Comment by NooberPro** [comment]
Just use comma after first link.
Like this
```js
site: 'https://nooberpro.gitbook.io/, https://nooberpro.gitbook.io ',
```
Any other problems

**Comment by Prokash18Paul** [comment]
sir i want it to be like this 
1 : https://nooberpro.gitbook.io/
2 : https://nooberpro.gitbook.io/
how can i do this ?

**Comment by NooberPro** [comment]
``` js
site: '\n1 : https://nooberpro.gitbook.io/ \n2 : https://nooberpro.gitbook.io ',
```
This will show like this 
```Link: 
1 : https://nooberpro.gitbook.io/
2 : https://nooberpro.gitbook.io/
```
If you want more control of the embeds go translation folder then your language folder then embeds then edit the text.

**Comment by Prokash18Paul** [comment]
sir i am faceing a new problem
![image](https://github.com/NooberPro/minecraft-discord-bot/assets/155884068/2e769466-8548-4e85-a53f-cfdb64bd25a9)
the white white thing

**Comment by NooberPro** [comment]
Did your issue fixed?
My english is not every good. 🙂

**Comment by NooberPro** [comment]
What plugins do you use.

**Comment by Prokash18Paul** [comment]
bro its not my server problem its the bot problem i guess
